Added new report option
puppetlabs/maintainers pull request #24
Opened 2016-10-18 23:47 UTC by theshanx

This commit adds an export flag to enagle GADS tooling.

2016-10-19 00:01 UTC, kylog commented
Hey @stahnma: in your copious spare time, are you interested in helping out with, ahem, maintenance of this maintainers gem?

2016-10-28 18:38 UTC, MikaelSmith commented on lib/maintainers/runner.rb
> -        report_people_details(maintainers_files)
I'm curious what changed on this line.

2016-10-28 18:40 UTC, MikaelSmith requested changes

2016-10-28 18:40 UTC, MikaelSmith commented on lib/maintainers/cli.rb
> +            opts.on("-d", "--details [repos|people|lists]", "detailed report") do |v|
We should update the help at line 56 (I was a little surprised it's not generated from opts).

2016-10-28 20:10 UTC, theshanx commented on lib/maintainers/runner.rb
> -        report_people_details(maintainers_files)
This is not the first time git has highlighted a non-existent diff (and I've never really dug into root causes for it)

2016-10-28 20:23 UTC, theshanx commented on lib/maintainers/cli.rb
> +            opts.on("-d", "--details [repos|people|lists]", "detailed report") do |v|
updated!

2016-10-28 20:25 UTC, MikaelSmith approved these changes

2016-10-28 20:25 UTC, merged