added github id to lists report
puppetlabs/maintainers pull request #28
Opened 2016-11-15 08:29 UTC by bcall

2016-11-15 19:06 UTC, MikaelSmith requested changes

2016-11-15 19:06 UTC, MikaelSmith commented on lib/maintainers/runner.rb
> +          list = "#{maintainers['internal_list']}"
Why did this change?

2016-11-15 19:06 UTC, MikaelSmith commented on lib/maintainers/runner.rb
> +            csv << [repo, list, name, github]
@theshanx is this something you need to know about?

2016-11-15 19:28 UTC, theshanx commented on lib/maintainers/runner.rb
> +            csv << [repo, list, name, github]
This should make it easier for IT to manage github teams - my only concern is with  line 183 - I think @bcall needs a header title...

2016-11-16 08:34 UTC, bcall commented
I've added the missing header label for the 'github' column. Does this look ok now?

2016-11-16 17:25 UTC, MikaelSmith approved these changes

2016-11-29 09:33 UTC, merged